choco install -y notepadplusplus
choco install -y winmerge
choco install -y sourcetree
choco install -y 7zip.install
choco install -y git.install
choco install -y fiddler
choco install -y keepass.install
choco install -y terminals
choco install -y slack
choco install -y skype
choco install -y googlechrome
choco install -y firefox
choco install -y opera
choco install -y sumatrapdf
choco install -y baretail
choco install -y visualstudio2015professional
choco install -y webstorm